package presentacion.vista;

import control.CJugador;
import control.CPartida;
import control.ControlBase;
import entidades.Dado;
import entidades.Jugador;
import entidades.Partida;
import entidades.Tablero;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JOptionPane;
import modelo.MPartida;
import modelo.ModeloBase;

/**
 * Frame de Creación de Partida.
 *
 * @author Equipo1
 */
public class FCrearPartida extends FrameBase {

    /**
     * Creates new form FCrearPartida
     */
    public FCrearPartida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resetDatos = new javax.swing.JButton();
        jButtonMenu = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        colorJugador = new javax.swing.JComboBox<>();
        nombreJugador = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tamanoTablero = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jSpinnerFondoJugador = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        cantidadJugadores = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jSpinnerMontoApuesta = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        cantidadFichas = new javax.swing.JComboBox<>();
        jButtonComenzar = new javax.swing.JButton();

        resetDatos.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        resetDatos.setForeground(new java.awt.Color(204, 0, 0));
        resetDatos.setText("Borrar");
        resetDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetDatosActionPerformed(evt);
            }
        });
        resetDatos.getAccessibleContext().setAccessibleDescription("");

        jButtonMenu.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButtonMenu.setForeground(new java.awt.Color(255, 0, 0));
        jButtonMenu.setText("Menu");
        jButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Creacion Partida");
        setMinimumSize(new java.awt.Dimension(629, 452));
        setResizable(false);
        setSize(new java.awt.Dimension(629, 452));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("Configuración partida");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(170, 10, 330, 30);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel2.setText("Escoga su color;");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(330, 110, 150, 30);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel3.setText("Datos del creador");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 60, 210, 20);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 40, 700, 10);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(0, 160, 700, 10);

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel8.setText("Escriba su apodo;");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 110, 170, 20);

        colorJugador.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        colorJugador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Azul", "Rosa", "Rojo", "Verde" }));
        jPanel1.add(colorJugador);
        colorJugador.setBounds(490, 110, 120, 30);

        nombreJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreJugadorActionPerformed(evt);
            }
        });
        jPanel1.add(nombreJugador);
        nombreJugador.setBounds(170, 110, 150, 30);

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel10.setText("Tamaño:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 180, 110, 30);

        tamanoTablero.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        tamanoTablero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "14", "12", "10" }));
        jPanel1.add(tamanoTablero);
        tamanoTablero.setBounds(170, 180, 120, 30);

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel11.setText("Fondo por jugador:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(320, 210, 170, 30);

        jSpinnerFondoJugador.setModel(new javax.swing.SpinnerNumberModel(1000, 1000, 2000, 50));
        jSpinnerFondoJugador.setEditor(new javax.swing.JSpinner.NumberEditor(jSpinnerFondoJugador, ""));
        jPanel1.add(jSpinnerFondoJugador);
        jSpinnerFondoJugador.setBounds(510, 210, 100, 30);

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel12.setText("Total Jugadores:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(10, 230, 150, 30);

        cantidadJugadores.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        cantidadJugadores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4" }));
        jPanel1.add(cantidadJugadores);
        cantidadJugadores.setBounds(170, 230, 120, 30);

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel9.setText("Monto apuesta:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(320, 270, 140, 30);

        jSpinnerMontoApuesta.setModel(new javax.swing.SpinnerNumberModel(100, 100, 750, 50));
        jSpinnerMontoApuesta.setEditor(new javax.swing.JSpinner.NumberEditor(jSpinnerMontoApuesta, ""));
        jPanel1.add(jSpinnerMontoApuesta);
        jSpinnerMontoApuesta.setBounds(510, 270, 100, 30);

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel7.setText("Total Fichas:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 280, 180, 30);

        cantidadFichas.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        cantidadFichas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6" }));
        jPanel1.add(cantidadFichas);
        cantidadFichas.setBounds(170, 280, 120, 30);

        jButtonComenzar.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButtonComenzar.setForeground(new java.awt.Color(0, 153, 0));
        jButtonComenzar.setText("Comenzar");
        jButtonComenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComenzarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonComenzar);
        jButtonComenzar.setBounds(260, 360, 120, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 630, 450);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuActionPerformed
        this.dispose();
        java.awt.EventQueue.invokeLater(() -> {
            new FInicio().setVisible(true);
        });
    }//GEN-LAST:event_jButtonMenuActionPerformed

    private void nombreJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreJugadorActionPerformed

    private void jButtonComenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComenzarActionPerformed
//      Partida partida2=new Partida(turno, tablero, montoJugador,montoApuesta, totalJugadores,cantidadFichas);
        Partida partida = new Partida(
                new Jugador(this.nombreJugador.getText(), this.colorJugador.getSelectedItem().toString()),
                new Tablero(Calendar.getInstance().get(Calendar.HOUR_OF_DAY) + "",
                        Integer.valueOf(this.tamanoTablero.getSelectedItem().toString())),
                ((Integer) this.jSpinnerFondoJugador.getValue()),
                ((Integer) this.jSpinnerMontoApuesta.getValue()),
                Integer.valueOf(this.cantidadJugadores.getSelectedItem().toString()),
                Integer.valueOf(this.cantidadFichas.getSelectedItem().toString())
        );
        ((CPartida) this.control).crearPartida(partida);
//        }
    }//GEN-LAST:event_jButtonComenzarActionPerformed

    private void resetDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetDatosActionPerformed
//        this.nombreJugador.setText("");
//        this.colorJugador.setSelectedIndex(0);
    }//GEN-LAST:event_resetDatosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cantidadFichas;
    private javax.swing.JComboBox<String> cantidadJugadores;
    private javax.swing.JComboBox<String> colorJugador;
    private javax.swing.JButton jButtonComenzar;
    private javax.swing.JButton jButtonMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner jSpinnerFondoJugador;
    private javax.swing.JSpinner jSpinnerMontoApuesta;
    private javax.swing.JTextField nombreJugador;
    private javax.swing.JButton resetDatos;
    private javax.swing.JComboBox<String> tamanoTablero;
    // End of variables declaration//GEN-END:variables
//

    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje);
    }
//Muestra la pantalla de lobby

    public void mostrarPantallaLobby(FLobby fLobby) {
        java.awt.EventQueue.invokeLater(() -> {
            fLobby.setVisible(true);
        });
    }
//Metodo que abre el lobby del creador con los datos de la partida

    @Override
    public void update(Observable o, Object o1) {
//        if (((MPartida) o).getPartida().getTurno().getNombre().isEmpty()) {
//            this.mostrarMensaje("Porfavor ingrese su nombre.");
//        } else {
        if (((MPartida) o).getPartida().isActiva()) {
//            this.dispose();
//            Partida partida = ((MPartida) o).getPartida();
//            JOptionPane.showMessageDialog(this, "Usted ha creado una partida; Nombre Escogigo=" + partida.getTurno().getNombre() + " Color; " + partida.getTurno().getColor());
//            ModeloBase modeloPartida = (MPartida) o;
//            ControlBase controlJugador = new CJugador();
//            controlJugador.establecerModelo(modeloPartida);
//            controlJugador.establecerCliente(this.control.getCliente());
////            this.control.getCliente().addObserver((Observer) modeloPartida);
//controlJugador.getCliente().addObserver((Observer) modeloPartida);
////            controlJugador.establecerCliente(this.control.getCliente());
//            FrameBase fLobby = new FLobby(((MPartida) o).getPartida().getMontoJugador(),
//                    ((MPartida) o).getPartida().getMontoApuesta(), ((MPartida) o).getPartida().getTablero().getTamano());
//            modeloPartida.deleteObserver(this);
//            fLobby.establecerControl(control);
//            modeloPartida.addObserver(fLobby);
//            ((FLobby) fLobby).apagarBoton();
//            ((FLobby) fLobby).actualizarLobby(((MPartida) o).getPartida().getJugadores());
//            this.mostrarPantallaLobby((FLobby) fLobby);

 this.dispose();
            Partida partida = ((MPartida) o).getPartida();
            JOptionPane.showMessageDialog(this, "Usted ha creado una partida; Nombre Escogigo=" + partida.getTurno().getNombre() + " Color; " + partida.getTurno().getColor());
            ModeloBase modeloPartida = (MPartida) o;
            ControlBase controlJugador = new CJugador();
            controlJugador.establecerModelo(modeloPartida);
            controlJugador.establecerCliente(this.control.getCliente());
            controlJugador.getCliente().addObserver((Observer) modeloPartida);
            FrameBase fLobby = new FLobby(((MPartida) o).getPartida().getMontoJugador(),
                    ((MPartida) o).getPartida().getMontoApuesta(), ((MPartida) o).getPartida().getTablero().getTamano());
            modeloPartida.deleteObserver(this);
             this.dispose();
            fLobby.establecerControl(controlJugador);
            modeloPartida.addObserver(fLobby);
            ((FLobby) fLobby).apagarBoton();
            ((FLobby) fLobby).actualizarLobby(((MPartida) o).getPartida().getJugadores());
            this.mostrarPantallaLobby((FLobby) fLobby);
this.control=null;
        } else {
            this.mostrarMensaje("No se ha podido establecer la creacion de la partida con el servidor, contacte a los creadores del servidor");
        }
//        }

    }
}
